name: Check
on:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s check
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: '~/**/test-results/**/*.xml'
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '~/**/test-results/**/*.xml'# Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results

