name: Check plugin
on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build_and_check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s check
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
