name: Check
on:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s check
#      - uses: actions/upload-artifact@v2  # upload test results
#        if: success() || failure()        # run this step even if previous step failed
#        with:
#          name: test-results
#          path: '~/**/test-results/**/*.xml'
      - name: Publish Unit Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            '*/build/test-results/**/*.xml'
            ./**/build/test-results/**/*.xml
            *.xml
            '~/**/test-results/**/*.xml'
            artifacts/**/*.xml


