name: Publish
on:
  release:
    types: [ published ]

jobs:
  publish:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64, task: publish }
          - { os: macos-latest, preset: macosX64, task: 'api:publishMacosX64PublicationToMavenRepository' }
          - { os: windows-latest, preset: mingwX64, task: 'api:publishMingwX64PublicationToMavenRepository' }
    name: Publish for ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - id: to_version
        uses: actions/github-script@0.9.0
        with:
          result-encoding: string
          script: |
            return '${{ github.event.release.tag_name }}'.replace(/^v/, '');
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        uses: eskatos/gradle-command-action@v1
        if: ${{ matrix.config.preset == 'linuxX64' }}
        with:
          arguments: -s test
      - name: Publish test report to artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: '~/**/test-results/**/*.xml'
      - name: Assemble Dist
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s distZip
      - name: Publish to Maven Repo
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s ${{ matrix.config.task }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.config.preset == 'linuxX64' }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/distributions/test2code-plugin-${{ steps.to_version.outputs.result }}.zip
          asset_name: test2code-plugin-${{ steps.to_version.outputs.result }}.zip
          asset_content_type: application/zip
