name: Build & publish coverage-plugin
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Publish coverage plugin as zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check
        run: gradle test
      - name: Publish
        run: |
          gradle -i publishTest2codeZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
