name: Build & publish coverage-plugin
on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Publish coverage plugin as zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: env
        run: env
      - name: Check
        run: gradle check
      - name: Publish
        run: |
          gradle --no-daemon -i publishCoverageZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}